metadata.format.version = "1.1"

[versions]

blossom = "2.2.0"
shadow = "8.1.1"
runtask = "3.0.2"

miniplaceholders = "3.1.0"
adventure = "4.26.1"
viaversion = "[5.6.0,5.7.0)"

[libraries]

miniplaceholders = { group = "io.github.miniplaceholders", name = "miniplaceholders-api", version.ref = "miniplaceholders" }

adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }

viaversion = { group = "com.viaversion", name = "viaversion-api", version.ref = "viaversion" }

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
runvelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runtask" }
